local files = {
	-- "autopairs",
	-- "better-escape",
	-- "comment",
	-- "conform",
	-- -- "debug",
	-- -- "emmet",
	-- "fff",
	-- "flash",
	-- "git-signs",
	-- "guttermarks",
	-- "indent",
	-- -- "lint",
	-- "lsp-saga",
	-- "markview",
	-- "mkmv",
	-- "mini",
	-- "neo-tree",
	-- "oil",
	-- "present",
	-- "rust",
	-- "surrounded",
	-- "symbol-outline",
	-- "table-mode",
	-- "tmux",
	-- "todo-comments",
	-- "typst",
	-- "visual-multi",
	"telescope",
	"treesitter",
	"which-key",
}
for _, file in pairs(files) do
	require("config.plugins." .. file)
end
